name: Collaborateive Workflow



on:
  push:
    branches:
      - main


jobs:
  update_html_and_readme:
    runs-on: ubuntu-latest
    steps:
      #step 1: checkout the repository
      - name: Checkout Repository
      - uses: actions/checkout@v3

      #step 2: update demo.html
          sed -i '/<\/body>/i <p>Updated by Team Leader on '"$(date)"'</p>' index.html

        
        
